[package]
name = "not_gdalwarp"
version = "0.0.1"
edition = "2021"
publish = false
authors = ["Jakub Lewandowski <scaleweather@gmail.com>"]
description = "Very simplistic implementation of GdalWarp"
repository = "https://github.com/ScaleWeather/NotGdalWarp"
readme = "README.md"
categories = ["mathematics", "science"]
license = "Apache-2.0"
exclude = [
    ".github/*",
]

[dependencies]
